### ISSUE TITLE
Error running Datahub ingestion sources -  "PermissionError: [Errno 13] Permission denied: '/tmp/datahub/ingest'\n"

### ISSUE THREAD

**Issue by vmm-afonso** [acryldata/datahub-helm#338]
I just recently installed Datahub using these charts and when I try to run ingestion of any source I get the same error message 

~~~~ Execution Summary - RUN_INGEST ~~~~
Execution finished with errors.
{'exec_id': 'f518fb5d-330d-4d05-8efd-0495467b0e9b',
 'infos': ['2023-07-03 11:01:32.611854 INFO: Starting execution for task with name=RUN_INGEST',
           '2023-07-03 11:01:32.614545 INFO: Caught exception EXECUTING task_id=f518fb5d-330d-4d05-8efd-0495467b0e9b, name=RUN_INGEST, '
           'stacktrace=Traceback (most recent call last):\n'
           '  File "/usr/local/lib/python3.10/site-packages/acryl/executor/execution/default_executor.py", line 122, in execute_task\n'
           '    task_event_loop.run_until_complete(task_future)\n'
           '  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete\n'
           '    return future.result()\n'
           '  File "/usr/local/lib/python3.10/site-packages/acryl/executor/execution/sub_process_ingestion_task.py", line 73, in execute\n'
           '    SubProcessTaskUtil._write_recipe_to_file(exec_out_dir, file_name, recipe)\n'
           '  File "/usr/local/lib/python3.10/site-packages/acryl/executor/execution/sub_process_task_common.py", line 121, in '
           '_write_recipe_to_file\n'
           '    os.makedirs(dir_path, mode = 0o777, exist_ok = True)\n'
           '  File "/usr/local/lib/python3.10/os.py", line 215, in makedirs\n'
           '    makedirs(head, exist_ok=exist_ok)\n'
           '  File "/usr/local/lib/python3.10/os.py", line 225, in makedirs\n'
           '    mkdir(name, mode)\n'
           "PermissionError: [Errno 13] Permission denied: '/tmp/datahub/ingest'\n"],
 'errors': []}



I checked and 'ingest/' doesn't exist inside the pods in /tmp/datahub, not sure if it's supposed to be creating that directory and for whatever reason is failing to do so

**Comment by lhoss** [comment]
Hi @vmm-afonso !
May I ask, how did you fix it ?

( I got the same issue deploying on a corporate Openshift environment .. my guess is  it's related to Openshift security(Context) stuff. Still diving into that )

**Comment by lhoss** [comment]
Your hints  helped me a lot 
Especially to look into the "actions" pod/container , because I was only focused on the "gms" container, from which above log originated (so I too early 99%-excluded  that the mkdir  could actually have failed in a diff container!).

Now in the actions container .. there's an existing /tmp/datahub directory, *of course* having a different dir owner ("datahub" your hint), than the  (Openshift) dynamically assigned container user UID .. which then explains (dir perm being r-x) the perm denied:
```
$ id
uid=1004900000(1004900000) gid=0(root) groups=0(root),1004900000

$ ls -la /tmp/datahub
total 0
drwxr-xr-x. 1 datahub datahub 18 Feb  8 18:06 .
drwxrwxrwt. 1 root    root    18 Apr 23 15:15 ..
drwxr-xr-x. 1 datahub datahub 21 Feb  8 18:06 logs

$ cat /etc/passwd | grep datahub

datahub:x:1000:1000:,,,:/datahub-ingestion:/bin/bash
```
With that the root cause is identified, and the fix not far..  thx again !
( Can I buy you a coffee .. send 10$ easily ?  I'm in Europe / Switzerl.  PM me if u want!)
(will need to check which SC I'm allowed to use .. with the SCCs setup by the Openshift cluster admins Team .. since I don't have admin permissions )

**Comment by vmm-afonso** [comment]
Hey @lhoss, 

 Glad you were able to identify the problem ;)

 I appreciate you for wanting to buy me a coffee hehe, I'm good tho, happy if that was helpful. 

Hope you don't run into other problems (with Datahub at least)
